name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:fix
      - name: Format
        run: npm run prettier
